### ISSUE TITLE
ValueError: not enough values to unpack (expected 2, got 1)

### ISSUE THREAD

**Issue by karel-brinda** [karel-brinda/mof-search#256]
```
$ m
make download
snakemake download --cores all --rerun-incomplete --printshellcmds --keep-going --use-conda --resources max_download_threads=8 max_io_heavy_threads=8 max_ram_mb=12288 30720 --cores 8 -j 8 --restart-times 3
Traceback (most recent call last):
  File "/Users/pseudokarel/miniconda/envs/snakemake/lib/python3.12/site-packages/snakemake/cli.py", line 2051, in main
    parser, args = parse_args(argv)
                   ^^^^^^^^^^^^^^^^
  File "/Users/pseudokarel/miniconda/envs/snakemake/lib/python3.12/site-packages/snakemake/cli.py", line 1641, in parse_args
    args = parser.parse_args(argv)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/pseudokarel/miniconda/envs/snakemake/lib/python3.12/site-packages/configargparse.py", line 797, in parse_args
    args, argv = self.parse_known_args(
                 ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/pseudokarel/miniconda/envs/snakemake/lib/python3.12/site-packages/configargparse.py", line 979, in parse_known_args
    namespace, unknown_args = argparse.ArgumentParser.parse_known_args(
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/pseudokarel/miniconda/envs/snakemake/lib/python3.12/argparse.py", line 1924, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/pseudokarel/miniconda/envs/snakemake/lib/python3.12/argparse.py", line 2136, in _parse_known_args
    start_index = consume_optional(start_index)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/pseudokarel/miniconda/envs/snakemake/lib/python3.12/argparse.py", line 2076, in consume_optional
    take_action(action, args, option_string)
  File "/Users/pseudokarel/miniconda/envs/snakemake/lib/python3.12/argparse.py", line 2000, in take_action
    action(self, namespace, argument_values, option_string)
  File "/Users/pseudokarel/miniconda/envs/snakemake/lib/python3.12/site-packages/snakemake/common/argparse.py", line 54, in __call__
    parsed = parse_func(values)
             ^^^^^^^^^^^^^^^^^^
  File "/Users/pseudokarel/miniconda/envs/snakemake/lib/python3.12/site-packages/snakemake/resources.py", line 585, in parse_resources
    for res, val in resources_args:
        ^^^^^^^^
ValueError: not enough values to unpack (expected 2, got 1)
make[1]: *** [download] Error 1
make: *** [all] Error 2
```

**Comment by karel-brinda** [comment]
Ok, a git related issue. THis part of the config was corrupted:
```
 57 <<<<<<< Updated upstream¬                                                                                                                                 
 58 # WARNING: this parameter is ignored when running on a cluster¬                                                                                           
 59 max_ram_gb: 12¬                                                                                                                                           
 60 ##################################################¬                                                                                                       
 61 ##################################################¬                                                                                                       
 62 # download¬                                                                                                                                               
 63 =======¬                                                                                                                                                  
 64 max_ram_gb: 30¬                                                                                                                                           
 65 >>>>>>> Stashed changes¬ 
```
